.TH YAD 1 "July 10, 2010"
.SH NAME
yad \- display GTK+ dialogs
.SH SYNOPSIS
.B yad
.RI [ options ]
.SH DESCRIPTION
\fBYad\fP is a program that will display GTK+ dialogs, and return
(either in the return code, or on standard output) the users
input. This allows you to present information, and ask for information
from the user, from all manner of shell scripts.
.PP
\fBYad\fP is the fork of \fBZenity\fP program.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').

.PP
Dialog options
.TP
.B \-\-calendar
Display calendar dialog.
.TP
.B \-\-color
Display color selection dialog.
.TP
.B \-\-dnd
Display drag-and-drop box.
.TP
.B \-\-entry
Display text entry dialog.
.TP
.B \-\-icons
Display box with shortcut icons.
.TP
.B \-\-file\-selection
Display file selection dialog.
.TP
.B \-\-form
Display form dialog
.TP
.B \-\-list
Display list dialog
.TP
.B \-\-notification
Display notification icon.
.TP
.B \-\-progress
Display progress indication dialog.
.TP
.B \-\-question
Display question dialog.
.TP
.B \-\-text-info
Display text information dialog.
.TP
.B \-\-scale
Display scale dialog.

.PP
General options
.TP
.B \-\-title=TITLE
Set the dialog title.
.TP
.B \-\-window-icon=ICONPATH
Set the window icon.
.TP
.B \-\-width=WIDTH
Set the dialog width.
.TP
.B \-\-height=HEIGHT
Set the dialog height.
.TP
.B \-\-timeout=TIMEOUT
Set the dialog timeout in seconds.
.TP
.B \-\-timeout-indicator=POSITION
Show timeout indicator in given position. Positions are \fItop\fP, \fIbottom\fP, \fIleft\fP or \fIright\fP.
Style of indicator may be set through gtkrc file. 
See http://code.google.com/p/yad/wiki/TimeoutIndicator for details.
.TP
.B \-\-text=STRING
Set the dialog text.
.TP
.B \-\-image=IMAGE
Set the dialog image which appears on the left side of dialog.
\fIIMAGE\fP might be file name or icon name from current icon theme.
.TP
.B \-\-image-on-top
Show image above main widget instead of left.
.TP
.B \-\-button=BUTTON:ID
Add the dialog button. May be used several times. \fIID\fP is an exit code.
\fIBUTTON\fP may be gtk stock item name for predefined buttons (like gtk-close or gtk-ok) or simple text label. 
Full list of stock items may be found in gtk-demo program, in snippet called \fI"Stock Items and Icon Browser"\fP. 
If no buttons specified \fIOK\fP and \fICancel\fP buttons used.
.TP
.B \-\-no-buttons
Don't show buttons.
.TP
.B \-\-dialog-sep
Show separator between dialog and buttons.
.TP
.B \-\-sticky
Make window visible on all desktops.
.TP
.B \-\-fixed
Make window fixed width and height.
.TP
.B \-\-center
Place window on center of screen.
.TP
.B \-\-mouse
Place window under mouse position.
.TP
.B \-\-on-top
Place window over other windows.
.TP
.B \-\-undecorated
Make window undecorated (remove title and window borders).

.PP 
Calendar options
.TP
.B \-\-day=INT
Set the calendar day.
.TP
.B \-\-month=INT
Set the calendar month.
.TP
.B \-\-year=INT
Set the calendar year.
.TP
.B \-\-date-format=PATTERN
Set the format for the returned date.

.PP 
Color options
.TP
.B \-\-value=COLOR
Set initial color value.
.TP
.B \-\-extra
Show extra information about color in returned string.
.TP
.B \-\-palette[=FILENAME]
Show palette ans set predefined colors from given filename.
By default used \fI/etc/X11/rgb.txt\fP.

.PP
Drag-and-Drop box options
.TP
.B \-\-command=CMD
Run command when data received. Data strings pass to command as an agrument. 
By default data just prints to stdout.

.PP
Text entry options
.TP
.B \-\-entry-text=STRING
Set the entry text.
.TP
.B \-\-hide-text
Hide the entry text.
.TP
.B \-\-completion
Use completion instead of combo-box.
.TP
.B \-\-editable
Allow changes to text in combo-box.

.PP
Iconbox options
.TP
.B \-\-read-dir=DIRECTORY
Read .desktop files from specified directory.
.TP
.B \-\-generic
Use field GenericName instead of Name for shortcut label.
.TP
.B \-\-stdin
Read data from stdin. Data must bi in order - \fIName\fP, \fITooltip\fP, \fIIcon\fP, \fICommand\fP, \fIInTerm\fP  separated by newline. \fIInTerm\fP is a case insensitive boolean value (true or false).
.TP
.B \-\-width
Set item width.
.TP
.B \-\-term
Pattern for terminal. By default use `xterm -e %s' where %s replaced by the command.

If both directory and stdin specified, content of iconbox will be read from directory.

.PP
File selection options
.TP
.B \-\-filename=FILENAME
Set the filename.
.TP
.B \-\-multiple
Allow selection of multiple filenames in file selection dialog.
.TP
.B \-\-directory
Activate directory-only selection.
.TP
.B \-\-save
Activate save mode.
.TP
.B \-\-separator=STRING
Specify separator character when returning multiple filenames.
.TP
.B \-\-confirm\-overwrite[=TEXT]
Confirm file selection if filename already exists. 
Optional argument is a text for confirmation dialog.

.PP
Form options
.TP
.B \-\-field=LABEL[:TYPE]
Add field to form. Type may be \fIH\fP for hidden fields or \fIRO\fP for read-only fields.
.TP
.B \-\-separator=STRING
Set output separator characters.
.PP
Additional data in command line interpret as a default values for form fields.

.PP
List options
.TP
.B \-\-column=STRING[:TYPE]
Set the column header. Types are \fITEXT\fP, \fINUM\fP, \fICHK\fP or \fIIMG\fP. 
\fITEXT\fP type is default.
Images may be path to image or icon name from currnet GTK+ icon theme.
Size of icons may be set in config file. Image field prints as empty value.
.TP
.B \-\-checklist
Use check boxes for first column.
.TP
.B \-\-separator=STRING
Set output separator characters.
.TP
.B \-\-multiple
Allow multiple rows to be selected.
.TP
.B \-\-editable
Allow changes to text.
.TP
.B \-\-print-all
Print all data from the list. 
.TP
.B \-\-print-column=NUM
Specify what column to print to standard output. \fI0\fP may be used to print all columns (this is default).
.TP
.B \-\-hide\-column=NUMBER
Hide a specific column.

.PP
Notification options
.TP
.B \-\-command=CMD
Set the command running when clicked on the icon.
.TP
.B \-\-listen
Listen for commands on stdin. See \fBNOTIFICATION\fP section.

.PP
Progress options
.PP
When the --progress option is used, yad reads lines of progress data from stdin. 
When the lines begin with \fI#\fP the text after \fI#\fP is displayed in the progress 
bar label. Numeric values treats like a persents for progress bar.    
.TP
.B \-\-progress-text=STRING
Set text in progress bar to STRING.
.TP
.B \-\-percentage=INT
Set initial percentage.
.TP
.B \-\-rtl
Set Right-To-Left progress bar direction.
.TP
.B \-\-auto\-close
Close dialog when 100% has been reached.
.TP
.B \-\-auto\-kill
Kill parent process if cancel button is pressed.
.TP
.B \-\-pulsate
Pulsate progress bar.

.PP
Text options
.TP
.B \-\-filename=FILENAME
Open specified file.
.TP
.B \-\-editable
Allow changes to text.
.TP
.B \-\-fore=COLOR
Set foreground color of text
.TP
.B \-\-back=COLOR
Set background color of text
.TP
.B \-\-font=FONT
Set text font. \fIFONT\fP must be in a Pango font description format.
.TP
.B \-\-wrap
Enable text wrapping.
.TP
.B \-\-tail
Autoscroll to end when new text appears. Works only when text is read from stdin.

.PP
Scale options
.TP
.B \-\-value=VALUE
Set initial value.
.TP
.B \-\-min\-value=VALUE
Set minimum value.
.TP
.B \-\-max\-value=VALUE
Set maximum value.
.TP
.B \-\-step=VALUE
Set step size.
.TP
.B \-\-print\-partial
Print partial values.
.TP
.B \-\-hide\-value
Hide value.

.PP
Miscellaneous options
.TP
.B \-?, \-\-help
Show summary of options.
.TP
.B \-\-about
Display an about dialog.
.TP
.B \-\-version
Show version of program.

.PP
Also the standard GTK+ options are accepted.

.SH NOTIFICATION
Allows commands to be sent yad in the form \fBcommand:args\fP.
Possible commands are \fIicon\fP, \fItooltip\fP, \fIvisible\fP, \fIaction\fP, \fImenu\fP and \fIquit\fP.
.TP
.B
icon:ICONNAME
Set notification icon to ICONNAME.
.TP
.B
tooltip:STRING
Set notification tooltip.
.TP
.B
visible:[true|false|blink]
Set notification icon to visible, invisible or blinking states.
.TP
.B
action:COMMAND
Specify the command running when double-clicked on the icon. 
Special string "quit" exit the program.
.TP
.B
menu:STRING
Set popup menu for notification icon.
STRING must be in form \fIname1!action1|name2!action2...\fP.
Empty name add separator to menu.
.TP
.B
quit
Exit the program.

.SH EXIT STATUS
.TP
.B
0
The user has pressed \fIOK\fP button
.TP
.B
1
The user has pressed \fICancel\fP button
.TP
.B
70
The dialog has been closed because the timeout has been reached.
.TP
.B
252
The dialog has been closed by pressing \fIEsc\fP or used the window functions to close the dialog
.TP
Exit codes for user-specified buttons must be specified in command line.

.SH EXAMPLES
Display a file selector with the title \fISelect a file to
remove\fP. The file selected is returned on standard output.
.IP
yad  \-\-title="Select a file to remove" \-\-file-selection
.PP
Display a text entry dialog with the title \fISelect Host\fP and the
text \fISelect the host you would like to flood-ping\fP. The entered
text is returned on standard output.
.IP
yad  \-\-title "Select Host" \-\-entry \-\-text "Select the host you would like to flood-ping"
.PP
Display a dialog, asking \fIMicrosoft Windows has been found! Would
you like to remove it?\fP. The return code will be 0 (true in shell)
if \fIYES\fP is selected, and 1 (false) if \fINO\fP is selected.
.IP
yad  \-\-image "dialog-question" \-\-title "Alert" \-\-button=gtk-yes:0 \-\-button=gtk-no:1 \-\-text "Microsoft Windows has been found! Would you like to remove it?"
.PP
Show the search results in a list dialog with the title \fISearch Results\fP
and the text \fIFinding all header files...\fP.
.IP
find . \-name '*.h' | yad \-\-list \-\-title "Search Results" \-\-text "Finding all header files.." \-\-column "Files"
.PP
Show an icon in the notification area
.IP
yad \-\-notification \-\-image=update.png \-\-text "System update necessary!" \-\-command "xterm -e apt-get upgrade"
.PP
Display a weekly shopping list in a check list dialog with \fIApples\fP and \fIOranges\fP pre selected
.IP
yad \-\-list \-\-checklist \-\-column "Buy" \-\-column "Item" TRUE Apples TRUE Oranges FALSE Pears FALSE Toothpaste
.PP
Display a progress dialog while searching for all the postscript files in your home directory
.IP
find $HOME \-name '*.ps' | yad \-\-progress \-\-pulsate
.PP
Display a box with all of the installed desktop applications
.IP
yad \-\-icons \-\-read-dir=/usr/share/applications

.SH AUTHOR
\fBYad\fP was written by Victor Ananjevsky <ananasik@gmail.com>.

.SH SEE ALSO
\fBgdialog\fP(1), \fBdialog\fP(1), \fBzenity\fP(1)
